# Generated by Django 4.0.2 on 2022-04-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirCooling',
            fields=[
                ('model_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('radiator_size', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('model_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('chassis_type', models.CharField(max_length=50)),
                ('form_factor', models.CharField(max_length=50)),
                ('top_radiator', models.CharField(max_length=50)),
                ('rear_radiator', models.CharField(max_length=50)),
                ('front_radiator', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('model_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('power_usage', models.IntegerField()),
                ('graphics', models.CharField(max_length=100)),
                ('chipset', models.CharField(max_length=50)),
                ('core_count', models.IntegerField()),
                ('core_clock', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('model_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('power_usage', models.IntegerField()),
                ('architecture', models.CharField(max_length=50)),
                ('chipset', models.CharField(max_length=50)),
                ('graphics', models.CharField(max_length=100)),
                ('ports', models.CharField(max_length=50)),
                ('bus_slots', models.CharField(max_length=50)),
                ('core_count', models.IntegerField()),
                ('core_clock', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LiquidCooling',
            fields=[
                ('model_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('height', models.CharField(max_length=50)),
                ('fan_output', models.CharField(max_length=50)),
                ('fan_speed', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('model_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('power_usage', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('speed', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('no_sticks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MotherBoard',
            fields=[
                ('model_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('power_usage', models.IntegerField()),
                ('form_factor', models.CharField(max_length=50)),
                ('chipset', models.CharField(max_length=50)),
                ('ports', models.CharField(max_length=50)),
                ('storage_capability', models.CharField(max_length=50)),
                ('pci_slots', models.CharField(max_length=50)),
                ('memory_type', models.CharField(max_length=50)),
                ('audio', models.CharField(max_length=50)),
                ('bluetooth', models.CharField(max_length=50)),
                ('lan', models.CharField(max_length=50)),
                ('wireless', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PowerSupply',
            fields=[
                ('model_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('modularity', models.CharField(max_length=50)),
                ('output', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('build_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('model_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('power_usage', models.CharField(max_length=50)),
                ('storage_size', models.CharField(max_length=50)),
                ('form_factor', models.CharField(max_length=50)),
                ('ports', models.CharField(max_length=50)),
                ('ssd', models.CharField(max_length=50)),
                ('hdd', models.CharField(max_length=50)),
                ('m2', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
