# Generated by Django 4.0.2 on 2022-04-08 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_aircooling_case_cpu_gpu_liquidcooling_memory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
