# Generated by Django 4.0.2 on 2022-04-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aircooling',
            old_name='location',
            new_name='fan_output',
        ),
        migrations.RenameField(
            model_name='aircooling',
            old_name='radiator_size',
            new_name='fan_speed',
        ),
        migrations.RenameField(
            model_name='liquidcooling',
            old_name='fan_output',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='liquidcooling',
            old_name='fan_speed',
            new_name='radiator_size',
        ),
        migrations.RemoveField(
            model_name='liquidcooling',
            name='height',
        ),
        migrations.AddField(
            model_name='aircooling',
            name='height',
            field=models.CharField(default=10, max_length=50),
            preserve_default=False,
        ),
    ]
