# Generated by Django 4.0.2 on 2022-04-09 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_aircooling_price_case_price_cpu_price_gpu_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('build_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('total_price', models.IntegerField()),
                ('build_cpu', models.CharField(max_length=50)),
                ('build_gpu', models.CharField(max_length=50)),
                ('build_motherboard', models.CharField(max_length=50)),
                ('build_psu', models.CharField(max_length=50)),
                ('build_ram', models.CharField(max_length=50)),
                ('build_storage1', models.CharField(max_length=50)),
                ('build_storage2', models.CharField(max_length=50)),
                ('build_case', models.CharField(max_length=50)),
                ('build_liquidCooling', models.CharField(max_length=50)),
                ('build_airCooling', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='build_id',
            field=models.IntegerField(),
        ),
    ]
