# Generated by Django 4.0.2 on 2022-04-13 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_delete_user_remove_build_build_id_build_build_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storage',
            old_name='hdd',
            new_name='speed',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='m2',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='ports',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='ssd',
        ),
    ]
