# Generated by Django 4.0.2 on 2022-04-13 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_delete_user_remove_build_build_id_build_build_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gpu',
            old_name='graphics',
            new_name='vram',
        ),
    ]
