# Generated by Django 4.0.2 on 2022-04-13 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_graphics_gpu_vram'),
        ('base', '0009_rename_hdd_storage_speed_remove_storage_m2_and_more'),
    ]

    operations = [
    ]
