# Generated by Django 4.0.2 on 2022-04-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_merge_20220413_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storage',
            old_name='speed',
            new_name='read_speed',
        ),
        migrations.AddField(
            model_name='storage',
            name='write_speed',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
    ]
